// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgeB0U5RmUWZTHZpZ5QbhGQ_yt6dAaT_Q',
    appId: '1:536236797897:web:6a003695f2345fd68c8218',
    messagingSenderId: '536236797897',
    projectId: 'umg-ra',
    authDomain: 'umg-ra.firebaseapp.com',
    storageBucket: 'umg-ra.firebasestorage.app',
    measurementId: 'G-ZMCYSKKN78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqQpR9NRWWgVdtdCPO4eZgADsUTkoR3Ro',
    appId: '1:536236797897:android:cbfe0b33bac53d358c8218',
    messagingSenderId: '536236797897',
    projectId: 'umg-ra',
    storageBucket: 'umg-ra.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLRGpM0y7XSBxwJ6QCjhOk9lpHpK7icbg',
    appId: '1:536236797897:ios:8127147f29a798e78c8218',
    messagingSenderId: '536236797897',
    projectId: 'umg-ra',
    storageBucket: 'umg-ra.firebasestorage.app',
    iosClientId: '536236797897-uodcbo8br10650b6a7mj3m6pr1b2l9an.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLRGpM0y7XSBxwJ6QCjhOk9lpHpK7icbg',
    appId: '1:536236797897:ios:8127147f29a798e78c8218',
    messagingSenderId: '536236797897',
    projectId: 'umg-ra',
    storageBucket: 'umg-ra.firebasestorage.app',
    iosClientId: '536236797897-uodcbo8br10650b6a7mj3m6pr1b2l9an.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgeB0U5RmUWZTHZpZ5QbhGQ_yt6dAaT_Q',
    appId: '1:536236797897:web:5a9603fdc3ecec528c8218',
    messagingSenderId: '536236797897',
    projectId: 'umg-ra',
    authDomain: 'umg-ra.firebaseapp.com',
    storageBucket: 'umg-ra.firebasestorage.app',
    measurementId: 'G-9B8FSCPXB3',
  );
}
